### ISSUE TITLE
If there are nested structures and common objects inside a structure, how should they be resolved?

### ISSUE THREAD

**Issue by lautnerxing** [Brokdar/ArxmlDataExtractor#13]
![pic](https://user-images.githubusercontent.com/51226709/236372391-87d2e2ee-8ff9-4e4c-b79a-4bf69199cbc9.png)
As shown in the following figure, signal_appears when I configure it with a ymal file 1 and signal_ Element of 2 is null because I want to resolve signal_ 3 adds an extra element reference.
![image](https://user-images.githubusercontent.com/51226709/236372690-44e794b2-fd99-40d8-b7d9-65e67421ccd4.png)

**Comment by lautnerxing** [comment]
And cannot output results in txt and xlsx formats, only JSON can succeed.
![image](https://user-images.githubusercontent.com/51226709/236372851-3d2a9180-a616-45db-a416-fd0664d0e923.png)
![pic2](https://user-images.githubusercontent.com/51226709/236373156-a271de6a-4ed7-426f-b8d0-041489cb171a.png)

**Comment by Brokdar** [comment]
I am sorry that the tool does not perform your task to your full satisfaction. I know that there are problems with nested objects. This was not a use case for me at the time and was therefore neglected.

Unfortunately, I have to inform you that I am no longer actively working on the project. However, you are welcome to modify the code to meet your use case.
